http:
  port: 3000
apiEndpoints:
  login:
    paths: '/auth/login'
    methods: ['POST']
serviceEndpoints:
  user-mangement:
    url: 'http://localhost:3001'
  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  user-management-endpoints:
    apiEndpoints:
      - login
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-mangement